CREATE TABLE [dbo].[Subscribers] (
	[Id] INT IDENTITY(1, 1) NOT NULL PRIMARY KEY,
	[Surname] NVARCHAR(25) NOT NULL,
	[Name] NVARCHAR(20) NOT NULL,
	[MiddleName] NVARCHAR(20) NOT NULL,
	[Gender] BIT NOT NULL,
	[Address] NVARCHAR(MAX) NOT NULL
);
